name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
    
    env:
      GRPC_INSTALL_DIR: ~/.grpc
      GRPC_VERSION: 1.32.0

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Get CMake Version
      id: cmake-version
      shell: bash
      run: |
        CMAKE_VERSION=$(cmake --version | grep -o "[0-9]*\.[0-9]*\.[0-9]*")
        echo ::set-output name=CMAKE_VERSION::${CMAKE_VERSION}

    - name: Cache grpc
      uses: actions/cache@v2
      id: grpc-cache
      with:
        path: ${{ env.GRPC_INSTALL_DIR }}
        key: ${{ runner.os }}-${{ matrix.build_type }}-grpc-${{ env.GRPC_VERSION }}-${{ steps.cmake-version.outputs.CMAKE_VERSION }}

    - name: Set up grpc
      if: steps.grpc-cache.outputs.cache-hit != 'true'
      run: |
        cmake -E make_directory ${{ env.GRPC_INSTALL_DIR }}
        git clone --depth 1 --recurse-submodules ---shallow-submodules -b v${{ env.GRPC_VERSION }} https://github.com/grpc/grpc
        cmake -E make_directory grpc/cmake/build
        cd grpc/cmake/build
        cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=${{ env.GRPC_INSTALL_DIR }} -DBENCHMARK_ENABLE_TESTING=OFF ../..
        cmake --build . --target install -j 8

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/
      run: |
        cmake -E make_directory build
        cd build
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=release -DCMAKE_PREFIX_PATH=${{ env.GRPC_INSTALL_DIR }}

    - name: Build Release
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: |
        cmake --build . --config release -j 4 --target sailgame

    - name: Create package
      id: package
      shell: bash
      run: |
        mkdir release
        cp build/sailgame release/
        cp GameDock/README.md release/
        cp GameDock/LICENSE release/
        PACKAGE_NAME=sailgame.gamedock.${GITHUB_REF#refs/tags/}.${{ matrix.os }}.tar.gz
        tar -czvf $PACKAGE_NAME -C release .
        echo ::set-output name=name::${PACKAGE_NAME}

    - name: Upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ../${{ steps.package.outputs.name }}
        asset_name: ${{ steps.package.outputs.name }}
        asset_content_type: application/gzip