name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        build_type: [debug, release]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Get CMake Version
      id: cmake-version
      shell: bash
      run: |
        CMAKE_VERSION=$(cmake --version | grep -o "[0-9]*\.[0-9]*\.[0-9]*")
        echo "CMAKE_VERSION=${CMAKE_VERSION}" >> $GITHUB_OUTPUT

    - name: Cache deps
      uses: actions/cache@v2
      id: deps-cache
      with:
        path: build/_deps
        key: ${{ runner.os }}-${{ matrix.build_type }}-${{ steps.cmake-version.outputs.CMAKE_VERSION }}-${{ hashFiles('externals/CMakeLists.txt') }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/
      run: |
        cmake -E make_directory build
        cd build
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=release -DCMAKE_PREFIX_PATH=${{ env.GRPC_INSTALL_DIR }}

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build/
      run: |
        cmake --build . --config ${{ matrix.build_type }} -j 4 --target sailgame

    - name: Test
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: ctest -L GameDock
