name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * * # daily at 00:00

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04]
        build_type: [debug, release]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v1
      with:
        path: boost_1_72_0/installdir
        key: ${{ runner.os }}-boost_1_72_0-fs-system-test

    - name: Install Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
        tar -zxf boost_1_72_0.tar.gz
        cd boost_1_72_0
        ./bootstrap.sh --with-libraries=filesystem,system,test
        ./b2 install

    - name: Create Build Environment
      working-directory: ${{runner.workspace}}
      run: |
        cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Cache externals
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/build/externals
        key: ${{ runner.os }}-build-${{ matrix.build_type }}-${{ hashFiles('externals/**/CMakeLists.txt') }}

    - name: Build
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: 
        cmake --build . --config ${{ matrix.node }} -j 4

    - name: Test
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: ctest -L GameDock
